---
layout: archive
title: "Publications"
permalink: /publications/
author_profile: true
---

{% include base_path %}

You can also find my articles on my [Google Scholar profile](https://scholar.google.com/citations?user=czTnYJQAAAAJ&hl=en).

24. Zhou, R. Z., Hu, Y., **Sun, K.**, Muldoon, R., Clark, S. & Joseph, K. (2025). [Explainable GeoAI and statistical analysis reveal complementary insights about disparities of 311 help requests during the 2022 Buffalo blizzard](https://www.sciencedirect.com/science/article/pii/S2212420925004595). *International Journal of Disaster Risk Reduction*, 126, 105635.  
23. **Sun, K.**, Hu, Y., Kenneth J., & Zhou, R. Z. (2025). [GALLOC: A GeoAnnotator for Labeling LOCation descriptions from disaster-related text messages](https://doi.org/10.1080/13658816.2025.2464643). *International Journal of Geographical Information Science*. In press.  
22. Qiu, Q., Li, H., Hu, X., Tian, M., Ma K., Zhu, Y., **Sun, K.\***, Li, W., Wang, S., & Xie, Z. (2024). [A knowledge-guided spatio-temporal correlation measure considering rules and dependency syntax for knowledge graph adaptive representation](https://onlinelibrary.wiley.com/doi/10.1111/tgis.13288). *Transactions in GIS*. In press.  
21. **Sun, K.**, Zhou, R. Z., Kim, J., & Hu, Y. (2024). [PyGRF: An improved Python Geographical Random Forest model and case studies in public health and natural disasters](https://doi.org/10.1111/tgis.13248). *Transactions in GIS*. In press.  
20. Li, W., **Sun, K.\***, Wang, S., Zhu, Y., Dai, X., & Hu, L. (2024). [DePNR: A DeBERTa-based deep learning model with complete position embedding for place name recognition from geographical literature](https://doi.org/10.1111/tgis.13170). *Transactions in GIS*. In press.  
19. **Sun, K.**, Hu, Y., Gaurish L., & Zhou, R. Z. (2023). [Spatial cross-validation for GeoAI](https://www.taylorfrancis.com/books/edit/10.1201/9781003308423), In: S. Gao, Y. Hu, and W. Li (Eds), *Handbook of Geospatial Artificial Intelligence*, Taylor & Francis Group.  
18. Zhu, Y., **Sun, K.\***, Wang, S., Zhou, C., Lu, F., Lv, H., Qiu, Q., Wang, X.,, & Qi, Y. (2023). [An Adaptive Representation Model for Geoscience Knowledge Graphs Considering Complex Spatiotemporal Features and Relationships](https://link.springer.com/article/10.1007/s11430-022-1169-9). *Science China Earth Sciences*, 66(11), 2563-2578.  
17. Li, W., **Sun, K.\***, Zhu, Y., Ding, F., Hu, L., Dai, X., Song, J., Yang, J., Qian, L., & Wang, S. (2023). [GeoTPE: A Neural Network Model for Geographical Topic Phrases Extraction from Literature Based on BERT Enhanced with Relative Position Embedding](https://www.sciencedirect.com/science/article/abs/pii/S0957417423015798). *Expert Systems with Applications*, 121077.  
16. **Sun, K.**, Hu, Y., Ma, Y., Zhou, R. Z., & Zhu, Y. (2023). [Conflating point of interest (POI) data: A systematic review of matching methods](https://www.sciencedirect.com/science/article/abs/pii/S0198971523000406). *Computers, Environment and Urban Systems*, 103, 101977.  
15. Dai, X., Zhu, Y., **Sun, K.\***, Zou, Q., Zhao, S., Li, W., Hu, L., & Wang, S. (2023). [Examining the Spatially Varying Relationships between Landslide Susceptibility and Conditioning Factors Using a Geographical Random Forest approach: A Case Study in Liangshan, China](https://www.mdpi.com/2072-4292/15/6/1513). *Remote Sensing*, 15(6), 1513.  
14. Wang, S., Yan, X., Zhu, Y., Song, J., **Sun, K.**, Li, W., Hu, L., Qi, Y., & Xu, H. (2022). [New Era for Geo-Parsing to Obtain Actual Locations: A Novel Toponym Correction Method Based on Remote Sensing Images](https://github.com/sunkai-8304/papers/blob/main/remotesensing-14-04725-v3.pdf). *Remote Sensing*, 14(19), 4725.  
13. Qiu, Q., Xie, Z., Wang, S., Zhu, Y., Lv, H., & **Sun, K.** (2022). [ChineseTR: A weakly supervised toponym recognition architecture based on automatic training data generator and deep neural network](https://onlinelibrary.wiley.com/doi/abs/10.1111/tgis.12902). *Transactions in GIS*, 26(3), 1256-1279.  
12. Zhu, Y., **Sun, K.\***, Hu, X., Lv, H., Wang, X., Yang, J., Wang, S., Li, W., Song, J., Su, N., & Mu, X. (2022). [Research and practice on the framework for the construction, sharing, and application of large-scale geoscience knowledge graphs](https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C45S0n9fL2suRadTyEVl2pW9UrhTDCdPD67jdIgJEUBVkpQ5fGS3jVevqCkUg_VgLBSQVAJbnaHaqmvIY68tyL8t&uniplatform=NZKPT). *Journal of Geo-information Science*, 25(6), 1215-1227. (in Chinese)   
11. Zhu, Y., **Sun, K.\***, Li, W., Wang, S., Song, J., Cheng, Q., Yang, J., Mu, X., Geng, W., Dai, X. (2021). [Comparative Analysis and Enlightenment of Geoscience Knowledge Graphs: A Perspective of Construction Methods and Contents](https://geology.nju.edu.cn/CN/10.16108/j.issn1006-7493.2021111). *Geological Journal of China Universities*, 29(3): 382-394. (in Chinese)   
10. **Sun, K.**, Hu, Y., Song, J., & Zhu, Y. (2021). [Aligning geographic entities from historical maps for building knowledge graphs](https://github.com/sunkai-8304/papers/blob/main/2020_IJGIS_MapGraph.pdf). *International Journal of Geographical Information Science*, 35(10), 2078-2107.  
9. Li, W., **Sun, K.**, Zhu, Y., Song, J., Yang, J., Qian, L., & Wang, S. (2021). [Analyzing the research evolution in response to COVID-19](https://github.com/sunkai-8304/papers/blob/main/ijgi-10-00237.pdf). *ISPRS International Journal of Geo-Information*, 10(4), 237-260.  
8. **Sun, K.**, Zhu, Y., Pan, P., Hou, Z., Wang, D., Li, W., & Song, J. (2019). [Geospatial data ontology: the semantic foundation of geospatial data integration and sharing](https://github.com/sunkai-8304/papers/blob/main/Geoontology.pdf). *Big Earth Data*, 3(3), 269-296.  
7. **Sun, K.**, Zhu, Y., & Song, J. (2019). [Progress and challenges on entity alignment of geographic knowledge bases](https://github.com/sunkai-8304/papers/blob/main/ijgi-08-00077-v2.pdf). *ISPRS International Journal of Geo-Information*, 8(2), 77-101.  
6. Yang, J., Zhu, Y., Song, J., Lu, F., **Sun, K.**, & Li, W. (2018). [A Precise Description Approach on the Result of Automatic Data Matching for Geo-spatial Model](https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7i0-kJR0HYBJ80QN9L51zrPyIFJyFxI5zlN7gx9OKK2HHyUoZRXb3edemsgjEfCX6O&uniplatform=NZKPT). *Journal of Geo-information Science*, 20(6), 744-752. (in Chinese)  
5. Zhu, Y., Zhu, A. X., Song, J., Yang, J., Feng, M., **Sun, K.**, Zhang J., Hou Z., & Zhao, H. (2017). [Multidimensional and quantitative interlinking approach for linked geospatial data](https://www.tandfonline.com/doi/full/10.1080/17538947.2016.1266041). *International Journal of Digital Earth*, 10(9), 923-943.  
4. Zhu, Y., Zhu, A. X., Feng, M., Song, J., Zhao, H., Yang, J., Zhang Q., **Sun K.**, Zhang J., & Yao, L. (2017). [A similarity-based automatic data recommendation approach for geographic models](https://www.tandfonline.com/doi/abs/10.1080/13658816.2017.1300805). *International Journal of Geographical Information Science*, 31(7), 1403-1424.  
3. Li, W., Zhu, Y., Song, J., **Sun, K.**, & Yang, J. (2017). [Geospatial Data Provenance Ontology and Its Application in Data Linking](https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7iAEhECQAQ9aTiC5BjCgn0RqcmulMbC3muQwUoKz1vcBXO_KgC89mXb12XpTWDiRZq&uniplatform=NZKPT). *Journal of Geo-information Science*, 19(10), 1261-1269. (in Chinese)  
2. **Sun, K.**, Zhu, Y., Pan, P., Luo, K., Wang, D., & Hou, Z. (2016). [Research on Morphology Ontology and Its Application in Geospatial Data Discovery](https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C44YLTlOAiTRKibYlV5Vjs7ijP0rjQD-AVm8oHBO0FTadgaYSZNlZqmZKss_73E-6hrtWwPtIa5i6YxW5rxa-PZT&uniplatform=NZKPT). *Journal of Geo-information Science*, 18(8), 1011-1021. (in Chinese)  
1. **Sun, K.**, Zhu, Y., Pan, P., Luo, K., Wang, D., & Hou, Z. (2015). [Morphology-ontology of geospatial data and its application in data discovery](https://ieeexplore.ieee.org/document/7378640). *In 2015 23rd International Conference on Geoinformatics*, 1-6.
